export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED';
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED';

export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_FULFILLED = 'SIGNIN_USER_FULFILLED';
export const SIGNIN_USER_PENDING = 'SIGNIN_USER_PENDING';
export const SIGNIN_USER_REJECTED = 'SIGNIN_USER_REJECTED';

export const CREATE_BUDGET = 'CREATE_BUDGET';
export const CREATE_BUDGET_FULFILLED = 'CREATE_BUDGET_FULFILLED';
export const CREATE_BUDGET_PENDING = 'CREATE_BUDGET_PENDING';
export const CREATE_BUDGET_REJECTED = 'CREATE_BUDGET_REJECTED';

export const FETCH_BUDGET = 'FETCH_BUDGET';
export const FETCH_BUDGET_FULFILLED = 'FETCH_BUDGET_FULFILLED';
export const FETCH_BUDGET_PENDING = 'FETCH_BUDGET_PENDING';
export const FETCH_BUDGET_REJECTED = 'FETCH_BUDGET_REJECTED';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_FULFILLED = 'CREATE_CATEGORY_FULFILLED';
export const CREATE_CATEGORY_PENDING = 'CREATE_CATEGORY_PENDING';
export const CREATE_CATEGORY_REJECTED = 'CREATE_CATEGORY_REJECTED';

export const CREATE_EXPANSE = 'CREATE_EXPANSE';
export const CREATE_EXPANSE_FULFILLED = 'CREATE_EXPANSE_FULFILLED';
export const CREATE_EXPANSE_PENDING = 'CREATE_EXPANSE_PENDING';
export const CREATE_EXPANSE_REJECTED = 'CREATE_EXPANSE_REJECTED';

export const FETCH_EXPANSE = 'FETCH_EXPANSE';
export const FETCH_EXPANSE_FULFILLED = 'FETCH_EXPANSE_FULFILLED';
export const FETCH_EXPANSE_PENDING = 'FETCH_EXPANSE_PENDING';
export const FETCH_EXPANSE_REJECTED = 'FETCH_EXPANSE_REJECTED';


export const REMOVE_EXPANSE = 'REMOVE_EXPANSE';
export const REMOVE_EXPANSE_FULFILLED = 'REMOVE_EXPANSE_FULFILLED';
export const REMOVE_EXPANSE_PENDING = 'REMOVE_EXPANSE_PENDING';
export const REMOVE_EXPANSE_REJECTED = 'REMOVE_EXPANSE_REJECTED';

export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_FULFILLED = 'REMOVE_CATEGORY_FULFILLED';
export const REMOVE_CATEGORY_PENDING = 'REMOVE_CATEGORY_PENDING';
export const REMOVE_CATEGORY_REJECTED = 'REMOVE_CATEGORY_REJECTED';

export const FETCH_EXPANSES_AND_DATES = 'FETCH_EXPANSES_AND_DATES';
export const FETCH_EXPANSES_AND_DATES_FULFILLED = 'FETCH_EXPANSES_AND_DATES_FULFILLED';
export const FETCH_EXPANSES_AND_DATES_PENDING = 'FETCH_EXPANSES_AND_DATES_PENDING';
export const FETCH_EXPANSES_AND_DATES_REJECTED = 'FETCH_EXPANSES_AND_DATES_REJECTED';

export const HANDLE_LOGOUT = 'HANDLE_LOGOUT';
export const FETCH_REFRESH_TOKEN = 'FETCH_REFRESH_TOKEN';
export const FETCH_REFRESH_TOKEN_FULFILLED = 'FETCH_REFRESH_TOKEN_FULFILLED';
export const FETCH_REFRESH_TOKEN_PENDING = 'FETCH_REFRESH_TOKEN_PENDING';
export const FETCH_REFRESH_TOKEN_REJECTED = 'FETCH_REFRESH_TOKEN_REJECTED';